import "./globals.css";
import Navbar from "../components/Navbar";
import ParallaxWrapper from "../components/ParallaxWrapper";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: "InFocusMedia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Almarai:wght@300;400;700;800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="relative">
        {/* 👇 Fixed background layer for mix-blend-difference to work */}
        {/* <div className="fixed inset-0 z-0 bg-red" /> */}

        <AuthProvider>
            <Navbar />
            {children}
        </AuthProvider>
      </body>
    </html>
  );
}
